PP-92 Fixing get contract for merge addresses
infuy/relaying-services-sdk pull request #8
Opened 2021-10-26 13:19 UTC by wilsoniovlabs

## What

- Review the SDK to find issues and fixed

## Why

- New error added when fix the contract addresses
- Review the SDK to find error to initialized (The error is to get all contracts from rif-relay-contracts json contract list file.

## Refs

- (optional: include links to other issues, PRs, tickets, etc)

2021-11-03 20:16 UTC, mortelli approved these changes
LGTM :+1: 

i would verify 2 things here:
1. see if the error bubbles up to the user in the dapp
2. verify `dist` is up-to-date

2021-11-03 20:17 UTC, mortelli commented
also @wilsoniovlabs: any particular reason why the package lock file is being included here?

2021-11-04 16:06 UTC, antomor requested changes
@wilsoniovlabs thanks for the changes.
Apart from the comment I left, it's not clear to me if the lib should be built whether with `npm run build` or with `npx webpack`. I cannot find the related section in the readme, so I would add some instructions about that. However, if one of the two methods is not required anymore, I would remove it.

2021-11-04 16:06 UTC, antomor commented on src/contracts.ts
> +        if (!contracts) {
I think that raising an error here won't allow the user to initialize the `Contracts` object.
We could move the error (maybe creating a custom error) in the `getContractAddresses` and catch the error here (maybe adding some warnings) to be able to complete the `Contracts` initialization.

2021-11-05 16:07 UTC, antomor requested changes
LGTM, Thank you @wilsoniovlabs! Just some minor changes before the approval.

2021-11-05 16:07 UTC, antomor commented on src/ContractError.ts
> +        super(msg);
```suggestion
        super(`ContractError: ${msg}`);
```

2021-11-05 16:07 UTC, antomor commented on src/ContractError.ts
> +        Object.setPrototypeOf(this, ContractError.prototype);
I like it, would you mind adding a reference to the reason behind this line?
```suggestion
        // https://github.com/Microsoft/TypeScript-wiki/blob/main/Breaking-Changes.md#extending-built-ins-like-error-array-and-map-may-no-longer-work
        Object.setPrototypeOf(this, ContractError.prototype);
```

2021-11-05 16:07 UTC, antomor commented on src/utils.ts
> +            `ContractError: contracts not find for the specified network id ${chainId}.`
If you accept the suggestion on the ContractError constructor:
```suggestion
            `No contracts found for the specified network id ${chainId}.`
```

2021-11-05 16:15 UTC, antomor approved these changes

2021-11-05 17:22 UTC, merged